name: CI

on:
  release:
    types: [published]

  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      RepositoryUrl: "https://github.com/${{ github.repository }}"
      RepositoryBranch: "${{ github.ref }}"
      SourceRevisionId: "${{ github.sha }}"
      Configuration: Release
      SolutionPath: AutoUpdaterTest.sln
      ArtifactPath: AutoUpdaterTest\bin\Release

    steps:
    
      - name: print env
        run: echo "${{ env.ArtifactPath }}"
        
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        id: MsBuildSetup

      - name: Restore NuGet Packages
        run: nuget restore ${{ env.SolutionPath }}


      - name: Build and Publish
        run: msbuild $env:SolutionPath /p:Configuration=Release
        
      - name: Zip Files
        uses: papeloto/action-zip@v1
        with:
          files: dist/ {{ env.ArtifactPath }}
          dest: result.zip
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: published_app
          path: result.zip
  
  upload:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      RepositoryUrl: "https://github.com/${{ github.repository }}"
      RepositoryBranch: "${{ github.ref }}"
      SourceRevisionId: "${{ github.sha }}"
      Configuration: Release
      SolutionPath: AutoUpdaterTest.sln
      ArtifactPath: AutoUpdaterTest\bin\Release

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: published_app
          path: published_app_path

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: published_app_path
      
      - name: upload
        uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: published_app_path
          container_name: $web
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          extra_args: '--destination-path ClickOnceTest1/'
          sync: false
